server:
  port: ${PORT:8080}

spring:
  application:
    name: skillbridge-graph
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

cognodb:
  uri: ${COGNODB_URI:bolt+s://db-e85d0a7b.databases.cognodb.com}
  username: ${COGNODB_USERNAME:cognodb}
  password: ${COGNODB_PASSWORD:}

app:
  seed-data: ${SEED_DATA:false}
